# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn run build
    - run: yarn test
    - run: yarn add --dev coveralls
    - run: yarn add -D handlebars@4.5.0
    - run: yarn run coverage

    - name: 'Qodana Scan'
      uses: JetBrains/qodana-action@main
      env:
        QODANA_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmdhbml6YXRpb24iOiIzd1dXciIsInByb2plY3QiOiJwOUxKdiIsInRva2VuIjoiQWFseUoifQ.0ld5coHnqvcDe9FC-9bztxj9KNzGv4ZdxCf3xpa1f-0
